from selenium.webdriver.common.by import By

from_field = (By.ID, 'from')
to_field = (By.ID, 'to')
btn_take_taxi = (By.XPATH, ".//div[@class='results-text']/button[text()='Pedir un taxi']")
btn_taxi_conford = (By.XPATH, ".//div[@class='tcard-icon']/img[@alt='Comfort']")
btn_add_phone = (By.CLASS_NAME, 'np-text')
number_phone_field = (By.ID, 'phone')
btn_continue = (By.XPATH, ".//div[@class='buttons']/button[text()='Siguiente']")
validation_code_field = (By.XPATH, ".//div[@class='input-container']/input[@id='code']")
btn_confirm = (By.XPATH, ".//div[@class='buttons']/button[text()='Confirmar']")
btn_add_payment_method = (By.XPATH, ".//div[@class='pp-value-container']/img[@alt='cash']")
btn_add_card = (By.XPATH, ".//div[@class='pp-plus-container']/img[@alt='plus']")
card_number_field = (By.ID, 'number')
card_code_field = (By.XPATH, ".//div[@class='card-code-input']/input[@id='code']")
div_img_card = (By.XPATH, ".//div[@class='card-second-row']/div[@class='plc']")
btn_save_card = (By.XPATH, ".//div[@class='pp-buttons']/button[text()='Agregar']")
btn_close_payment_method = (By.XPATH, "/html/body/div/div/div[2]/div[2]/div[1]/button")
message_for_driver_field = (By.ID, 'comment')
btn_add_blanket_and_scarves = (By.XPATH, "/html/body/div/div/div[3]/div[3]/div[2]/div[2]/div[4]/div[2]/div[1]/div/div[2]/div/span")
btn_add_ice_cream = (By.XPATH, "/html/body/div/div/div[3]/div[3]/div[2]/div[2]/div[4]/div[2]/div[3]/div/div[2]/div[1]/div/div[2]/div/div[3]")
div_count_ice_cream = (By.XPATH, "/html/body/div/div/div[3]/div[3]/div[2]/div[2]/div[4]/div[2]/div[3]/div/div[2]/div[1]/div/div[2]/div/div[2]")
btn_order_taxi = (By.XPATH, "/html/body/div/div/div[3]/div[4]/button")
div_selected_drive = (By.XPATH, "/html/body/div/div/div[5]/div[2]/div[2]/div[1]/div[1]/div[1]")
div_first_requirements = (By.XPATH, "/html/body/div/div/div[3]/div[3]/div[2]/div[2]/div[4]/div[2]/div[1]/div/div[1]")
div_text_card = (By.XPATH, "/html/body/div/div/div[2]/div[2]/div[1]/div[2]/div[3]/div[2]")
text_div_form_searching_taxi = (By.XPATH, "/html/body/div/div/div[5]/div[2]/div[1]/div/div[1]")